#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config normal_border_color "#337ab7"
bspc config border_width         2
bspc config window_gap          13
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a termite state=floating
bspc rule -a mpv desktop='^6'

yabar &
setxkbmap -layout us,ir -option 'grp:alt_shift_toggle'
feh --bg-scale ~/Pictures/wallpapers/2100153-l_deathnote.jpg 
synclient TapButton1=1
