require 'nvim-treesitter.configs'.setup {
    ensure_installed = {
        "c",
        "cpp",
        "lua",
        "vim",
        "vimdoc",
        "query",
        "python",
        "go",
        "bash",
        "yaml",
        "make",
        "json",
        "toml",
        "rust",
        "haskell",
        "sql",
        "dockerfile",
        "csv",
        "zig",
        "nginx",
        "html",
        "css",
        "javascript",
        "typescript",
        "markdown",
        "caddy",
        "php",
    },
    sync_install = false,
    auto_install = true,

    highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
    },
    ignore_install = {},
    modules = {},
}
